ALTER TABLE error_logs
  ADD COLUMN IF NOT EXISTS source TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS category TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS job_id TEXT DEFAULT NULL;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'openrouter_usage') THEN
    EXECUTE 'ALTER TABLE openrouter_usage ADD COLUMN IF NOT EXISTS prompt_tokens INTEGER DEFAULT NULL';
    EXECUTE 'ALTER TABLE openrouter_usage ADD COLUMN IF NOT EXISTS completion_tokens INTEGER DEFAULT NULL';
    EXECUTE 'ALTER TABLE openrouter_usage ADD COLUMN IF NOT EXISTS total_tokens INTEGER DEFAULT NULL';
    EXECUTE 'ALTER TABLE openrouter_usage ADD COLUMN IF NOT EXISTS cost_usd NUMERIC(10,6) DEFAULT NULL';
  END IF;
END $$;